title = 'General Weighted Matching'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/171"

[[tests]]
    name = "example.in"
    number = 2
[[tests]]
    name = "minimal.in"
    number = 1
[[tests]]
    name = "issue610.in"
    number = 1
[[tests]]
    name = "anti53256.in"
    number = 1
[[tests]]
    name = "small_random.cpp"
    number = 2
[[tests]]
    name = "max_random.cpp"
    number = 2
[[tests]]
    name = "sparse.cpp"
    number = 5
[[tests]]
    name = "binary_tree.cpp"
    number = 1
[[tests]]
    name = "cycles.cpp"
    number = 1
[[tests]]
    name = "grid.cpp"
    number = 1
[[tests]]
    name = "complete.cpp"
    number = 1
[[tests]]
    name = "lila_arena.cpp"
    number = 1

[params]
    N_MIN = 1
    N_MAX = 500
    W_MIN = 1
    W_MAX = 1_000_000

